version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      REACT_APP_API_URL: http://localhost:8080
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
